version: '3.6'
services:
    app:
        build:
            context: ./app
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - IFTTT_WEBHOOK_API_KEY=${IFTTT_WEBHOOK_API_KEY}
            - APIXU_API_KEY=${APIXU_API_KEY}
        ports:
            - "5000:5000"
    redis:
        image: redis:3.2-alpine
        volumes:
            - redis_data:/data
volumes:
    redis_data: